name: Deploy Hakyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1.
    - uses: actions/checkout@v3

    # 2. Cachear las dependencias de Stack (Ahorra mucho tiempo)
    - name: Cache .stack
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    # 3. Instalar GHC y Stack
    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-no-global: true

    # 4. Compilar el sitio (Esto tarda la primera vez)
    - name: Build site
      run: stack build

    # 5. Generar el HTML (Ejecuta tu site.hs)
    - name: Generate site
      run: stack exec site build

    # 6. Publicar a la rama 'gh-pages' autom√°ticamente
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true # Mantiene la rama de deploy limpia
